### ISSUE TITLE
npm test polutes log with many errors

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms#221] opened 2023-07-12 16:59 UTC
See example log here:
https://github.com/kbss-cvut/s-forms/actions/runs/5534301619/jobs/10099066069?pr=220

Example errors:
![image](https://github.com/kbss-cvut/s-forms/assets/3962237/7a0d2b71-64aa-4918-9742-a6f2795357f5)

**Comment by VojtechLunak** [comment] 2023-07-13 07:44
@blcham Might be duplicate of #176

**Comment by LaChope** [comment] 2023-09-25 14:27
To resolve this logs: 

![image](https://github.com/kbss-cvut/s-forms/assets/57750426/f9f5e7e2-3f83-40dd-8c71-842aec829b62)

From [react documentation](https://legacy.reactjs.org/docs/test-utils.html#act), a component must be prepared for assertion using [act()](https://legacy.reactjs.org/docs/test-utils.html#act). It is usually already integrated in [React-testing librabry](https://testing-library.com/docs/dom-testing-library/api-async/#waitfor), but in case of asynchronous updates, it must be wrapped in [waitFor()](https://davidwcai.medium.com/react-testing-library-and-the-not-wrapped-in-act-errors-491a5629193b). See #229

**Closed** 2023-09-25 14:35 UTC
